services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: nexusfin
      POSTGRES_PASSWORD: nexusadmin
      POSTGRES_DB: rootDatabase
    ports:
      - "5432:5432"
    
volumes:
  pgdata:
