services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: nexusfin
      POSTGRES_PASSWORD: nexusadmin
      POSTGRES_DB: rootDatabase
    ports:
      - "5432:5432"
    command:
      postgres -c log_min_messages=warning
    
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "3001:3001"
    environment:
      NODE_ENV: production
      databaseUrl: postgres://nexusfin:nexusadmin@database:5432/rootDatabase
      JWT_KEY: 8tNv5J6A7g5UplF0omFn

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    environment:
      NODE_ENV: production
    
volumes:
  pgdata:
