services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: nexusfin
      POSTGRES_PASSWORD: nexusadmin
      POSTGRES_DB: rootDatabase
    ports:
      - "5432:5432"
    
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    environment:
      NODE_ENV: production

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    environment:
      - databaseUrl=postgres://nexusfin:nexusadmin@database:5432/rootDatabase

    
volumes:
  pgdata:
